Remove outdated hardfork banner
aeonix/aeonix.github.io pull request #109
Opened 2021-01-12 02:42 UTC by SomaticFanatic

2021-01-12 15:52 UTC, ivoryguru approved these changes

2021-01-12 18:12 UTC, ivoryguru requested changes
https://github.com/SomaticFanatic/aeonix.github.io/pull/1

2021-01-13 18:52 UTC, ivoryguru approved these changes

2021-01-13 19:01 UTC, SomaticFanatic commented
@iamsmooth Please merge

2021-01-13 21:26 UTC, ivoryguru commented
Smooth always merges at an appropriate time. It is good to let it wait to see if there is anyone who would like to view the changes or make additional suggestions.

2021-01-13 21:49 UTC, merged